SELECT
    YEAR(POSTED) + 1 AS YEAR_POSTED,
    COUNTY AS AREAID,
    NAICS6 AS INDID,
    SOC_5 AS OCCID,
    COMPANY,
    MIN_EDULEVELS,
    IS_INTERNSHIP,
    COUNT(*) AS CURR_NUM_JOBS,
    SUM(DURATION) AS CURR_TOTAL_DURATION,
    COUNT(DURATION) AS CURR_N_WITH_DURATION,
    SUM(DUPLICATES + 1) AS CURR_TOTAL_TIMES_JOB_POSTED,
    SUM(SALARY) AS CURR_TOTAL_SALARY,
    COUNT(SALARY) AS CURR_N_WITH_SALARY
FROM LIGHTCAST.TULSA_FOR_YOU.POSTINGS
WHERE
    COMPANY_IS_STAFFING = FALSE
GROUP BY
    YEAR_POSTED,
    AREAID,
    COMPANY,
    INDID,
    OCCID,
    MIN_EDULEVELS,
    IS_INTERNSHIP
