/*
---------------------------------------------------------------------------------------------------
--
-- Description: 
--
-- Author:          Nile Dixon
-- Date:            2025-11-18
--
-- Notes:
-- 
--
--
---------------------------------------------------------------------------------------------------
*/

WITH ACS_DATA AS (
    SELECT 
        AREAID, 
        AREAID_NAME, 
        MEDIAN_HOUSEHOLD_INCOME, 
        POVERTY_LEVEL_PCT 
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_ACS_INDICATORS
    WHERE
        AREAID_TYPE = 'COUNTY'
),
-- Retrieve Labor Force Participation Rate, Unemployment Rate and Number Employed for Current Year
CURR_YEAR AS (
    SELECT
        AREAID,
        AREAID_NAME,
        LFP_DENOM,
        AVG((EMP + UNEMP) / POP) AS LFPR, -- LFP_DENOM / POP (GABE CHANGED)
        ROUND(AVG(UNEMP),0) AS UNEMP,
        AVG(UNEMP / (EMP + UNEMP)) AS UNEMPR, -- UNEMP / LFP_DENOM (GABE CHANGED)
        ROUND(AVG(EMP),0) AS EMP

    FROM LIGHTCAST.TULSA_FOR_YOU.DAT_LABOR_FORCE
    WHERE
        AREAID_TYPE = 'COUNTY'
        AND YEAR = 2025
        -- AND MONTH = MONTH(CURRENT_DATE()) - 3 (GABE CHANGED by COMMENTING LINE)
    GROUP BY
        AREAID,
        AREAID_NAME,
        LFP_DENOM
),

-- Retrieve Labor Force Participation Rate, Unemployment Rate and Number Employed for Previous Year
PRIOR_YEAR AS (
    SELECT
        AREAID,
        AREAID_NAME,
        LFP_DENOM,
        AVG((EMP + UNEMP) / POP) AS LFPR, -- LFP_DENOM / POP (GABE CHANGED)
        ROUND(AVG(UNEMP),0) AS UNEMP,
        AVG(UNEMP / (EMP + UNEMP)) AS UNEMPR, -- UNEMP / LFP_DENOM (GABE CHANGED)
        ROUND(AVG(EMP),0) AS EMP
    FROM LIGHTCAST.TULSA_FOR_YOU.DAT_LABOR_FORCE
    WHERE
        AREAID_TYPE = 'COUNTY'
        AND YEAR = 2024
        -- AND MONTH = MONTH(CURRENT_DATE()) - 3 (GABE CHANGED by COMMENTING LINE)
    GROUP BY
        AREAID,
        AREAID_NAME,
        LFP_DENOM
),
-- Retrieve Population for Current Year
CURR_YEAR_POP AS (
    SELECT
        YEAR,
        AREAID,
        AREAID_NAME,
        ROUND(SUM(POP),0) AS POPULATION
    FROM
        LIGHTCAST.TULSA_FOR_YOU.DAT_DEMOG
    WHERE
        AGEID LIKE 'G%'
        AND RACEID = 0
        AND GENDERID = 0
        AND AREAID_TYPE = 'COUNTY'
        AND YEAR = 2024 -- GABE CHANGED
    GROUP BY
        YEAR,
        AREAID,
        AREAID_NAME
),

-- Retrieve Population for Previous Year
PRIOR_YEAR_POP AS (
    SELECT
        YEAR,
        AREAID,
        AREAID_NAME,
        ROUND(SUM(POP),0) AS POPULATION
    FROM
        LIGHTCAST.TULSA_FOR_YOU.DAT_DEMOG
    WHERE
        AGEID LIKE 'G%'
        AND RACEID = 0
        AND GENDERID = 0
        AND AREAID_TYPE = 'COUNTY'
        AND YEAR = 2023 -- GABE CHANGED
    GROUP BY
        YEAR,
        AREAID,
        AREAID_NAME
),

-- Retrieve Number of Job Postings for Current Year
CURR_JOB_POSTINGS AS (
    SELECT
        YEAR(POSTED) AS YEAR,
        COUNTY AS AREAID,
        COUNTY_NAME AS AREAID_NAME,
        COUNT(*) AS NUM_POSTINGS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.POSTINGS
    WHERE
        YEAR(POSTED) = YEAR(CURRENT_DATE())
    GROUP BY 
        YEAR,
        AREAID,
        AREAID_NAME
),

-- Retrieve Number of Job Postings for Prior Year
PRIOR_JOB_POSTINGS AS (
    SELECT
        YEAR(POSTED) AS YEAR,
        COUNTY AS AREAID,
        COUNTY_NAME AS AREAID_NAME,
        COUNT(*) AS NUM_POSTINGS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.POSTINGS
    WHERE
        YEAR(POSTED) = YEAR(CURRENT_DATE())
    GROUP BY 
        YEAR,
        AREAID,
        AREAID_NAME
),

-- Retrieve Number of Job Postings for Last 365 days
CURR_ROLLING_JOB_POSTINGS AS (
    SELECT
        COUNTY AS AREAID,
        COUNTY_NAME AS AREAID_NAME,
        COUNT(*) AS NUM_POSTINGS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.POSTINGS
    WHERE
        DATEDIFF(YEAR, POSTED::DATE, CURRENT_DATE()) < 1
    GROUP BY 
        AREAID,
        AREAID_NAME
),

-- Retrieve Number of Job Postings for Prior 365 day period
PRIOR_ROLLING_JOB_POSTINGS AS (
    SELECT
        COUNTY AS AREAID,
        COUNTY_NAME AS AREAID_NAME,
        COUNT(*) AS NUM_POSTINGS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.POSTINGS
    WHERE
        DATEDIFF(YEAR, POSTED::DATE, CURRENT_DATE()) >= 1
        AND DATEDIFF(YEAR, POSTED::DATE, CURRENT_DATE()) < 2
    GROUP BY 
        AREAID,
        AREAID_NAME
),

-- Retrieve Number of Enrollment for most recent year
CURR_ENROLLMENT AS (
    SELECT 
        EN.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(EN.ENROLLMENTS) AS ENROLLMENTS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_ENROLLMENTS AS EN
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        EN.UNITID = DIM_UID.UNITID
    WHERE
        EN.RACEID = 0
        AND EN.GENDERID = 0
        AND EN.ENRLEVELID = 1
        AND EN.YEAR = (SELECT MAX(YEAR) FROM LIGHTCAST.TULSA_FOR_YOU.DAT_ENROLLMENTS)
    GROUP BY
        YEAR,
        AREAID
),

-- Retrieve Number of Enrollment for second most recent year
PRIOR_ENROLLMENT AS (
    SELECT 
        EN.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(EN.ENROLLMENTS) AS ENROLLMENTS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_ENROLLMENTS AS EN
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        EN.UNITID = DIM_UID.UNITID
    WHERE
        EN.RACEID = 0
        AND EN.GENDERID = 0
        AND EN.ENRLEVELID = 1
        AND EN.YEAR = (SELECT MAX(YEAR) - 1 FROM LIGHTCAST.TULSA_FOR_YOU.DAT_ENROLLMENTS)
    GROUP BY
        YEAR,
        AREAID
),
CURR_ASSOC AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND 
        CD.AWLEVELID = 3 
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
PRIOR_ASSOC AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND
        CD.AWLEVELID = 3 
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) - 1 FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
CURR_BACH AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND 
        CD.AWLEVELID = 5
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
PRIOR_BACH AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND
        CD.AWLEVELID = 5
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) - 1 FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
CURR_MASTERS AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND
        CD.AWLEVELID = 7
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
PRIOR_MASTERS AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND
        CD.AWLEVELID = 7
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) - 1 FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
CURR_DOCTORS AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND 
        CD.AWLEVELID = 9
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
PRIOR_DOCTORS AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND 
        CD.AWLEVELID = 9
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) - 1 FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
CURR_CERTS AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND 
        CD.AWLEVELID = 11
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
),
PRIOR_CERTS AS (
    SELECT 
        CD.YEAR AS YEAR,
        DIM_UID.COUNTY AS AREAID,
        SUM(CD.COMPLETIONS) AS COMPLETIONS
    FROM 
        LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS AS CD 
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_UNITID AS DIM_UID
    ON
        CD.UNITID = DIM_UID.UNITID
    LEFT JOIN 
        LIGHTCAST.TULSA_FOR_YOU.DIM_PROGRAMID AS DP 
    ON 
        CD.PROGRAMID = DP.PROGRAMID
    WHERE 
        DP.LEVEL = 3 AND 
        CD.AWLEVELID = 11
        AND RACEID = 0
        AND GENDERID = 0
        AND YEAR = (
            SELECT MAX(YEAR) - 1 FROM LIGHTCAST.TULSA_FOR_YOU.DAT_COMPLETIONS_DEMOGRAPHICS
        )
    GROUP BY
        YEAR,
        AREAID
)

SELECT
    CURR_YEAR.AREAID AS AREAID,
    CURR_YEAR.AREAID_NAME AS COUNTY_NAME,
    CURR_YEAR.EMP + CURR_YEAR.UNEMP AS CURRENT_YEAR_LABOR_FORCE, -- FF.1.1 (GABE CHANGED)
    PRIOR_YEAR.EMP + PRIOR_YEAR.UNEMP AS PRIOR_YEAR_LABOR_FORCE, -- (GABE CHANGED)
    CURR_YEAR.LFPR AS CURRENT_LABOR_FORCE_PARTICIPATION_RATE, -- FF.1.2
    PRIOR_YEAR.LFPR AS PRIOR_LABOR_FORCE_PARTICIPATION_RATE,
    CURRENT_YEAR_LABOR_FORCE - PRIOR_YEAR_LABOR_FORCE AS RAW_CHANGE_IN_LABOR_FORCE, -- FF.1.3
    (CURRENT_YEAR_LABOR_FORCE - PRIOR_YEAR_LABOR_FORCE) / PRIOR_YEAR_LABOR_FORCE AS PCT_CHANGE_IN_LABOR_FORCE,-- FF.1.3
    CURR_YEAR.UNEMP AS CURRENT_UNEMPLOYED, -- FF.2.1
    PRIOR_YEAR.UNEMP AS PRIOR_UNEMPLOYED,
    CURR_YEAR.UNEMPR AS CURRENT_UNEMPLOYMENT_RATE, -- FF.2.2
    PRIOR_YEAR.UNEMPR AS PRIOR_UNEMPLOYMENT_RATE,
    (CURRENT_UNEMPLOYMENT_RATE - PRIOR_UNEMPLOYMENT_RATE) / (PRIOR_UNEMPLOYMENT_RATE) AS PCT_CHANGE_IN_UNEMPLOYMENT_RATE, -- FF.2.3
    CURR_YEAR.EMP AS CURRENT_EMPLOYED, -- FF.3.1
    PRIOR_YEAR.EMP AS PRIOR_EMPLOYED, 
    CURRENT_EMPLOYED - PRIOR_EMPLOYED AS CHANGE_IN_EMPLOYED, -- FF.3.2
    CURR_YEAR_POP.POPULATION AS CURRENT_POPULATION, -- FF.4.1
    PRIOR_YEAR_POP.POPULATION AS PRIOR_POPULATION,
    CURRENT_POPULATION - PRIOR_POPULATION AS RAW_CHANGE_IN_POPULATION, -- FF.4.2
    (CURRENT_POPULATION - PRIOR_POPULATION) / PRIOR_POPULATION AS PCT_CHANGE_IN_POPULATION, -- FF.4.2
    ACS_DATA.MEDIAN_HOUSEHOLD_INCOME AS MEDIAN_HOUSEHOLD_INCOME, -- FF.5.1
    CURR_JOB_POSTINGS.NUM_POSTINGS AS CURRENT_NUMBER_POSTINGS, -- FF.6.1
    CURR_ROLLING_JOB_POSTINGS.NUM_POSTINGS AS CURRENT_ROLLING_NUMBER_POSTINGS,
    PRIOR_ROLLING_JOB_POSTINGS.NUM_POSTINGS AS PRIOR_ROLLING_NUMBER_POSTINGS,
    (CURRENT_ROLLING_NUMBER_POSTINGS - PRIOR_ROLLING_NUMBER_POSTINGS) / PRIOR_ROLLING_NUMBER_POSTINGS AS PCT_CHANGE_NUMBER_POSTINGS, -- FF.6.2
    COALESCE(CURR_ENROLLMENT.ENROLLMENTS,0) AS CURRENT_NUMBER_ENROLLED, -- FF.7.1
    COALESCE(PRIOR_ENROLLMENT.ENROLLMENTS,0) AS PRIOR_NUMBER_ENROLLED,
    CURRENT_NUMBER_ENROLLED - PRIOR_NUMBER_ENROLLED AS RAW_CHANGE_ENROLLED, -- FF.7.2
    DIV0((CURRENT_NUMBER_ENROLLED - PRIOR_NUMBER_ENROLLED),(PRIOR_NUMBER_ENROLLED)) AS PCT_CHANGE_ENROLLED, -- FF.7.2
    COALESCE(CURR_ASSOC.COMPLETIONS,0) AS CURRENT_ASSOC_COMPLETIONS, -- FF.7.3
    COALESCE(CURR_BACH.COMPLETIONS,0) AS CURRENT_BACH_COMPLETIONS, -- FF.7.3
    COALESCE(CURR_CERTS.COMPLETIONS,0) AS CURRENT_CERT_COMPLETIONS, -- FF.7.3
    COALESCE(CURR_MASTERS.COMPLETIONS,0) AS CURRENT_MASTERS_COMPLETIONS, -- FF.7.3
    COALESCE(CURR_DOCTORS.COMPLETIONS,0) AS CURRENT_DOCTORS_COMPLETIONS, -- FF.7.3
    COALESCE(PRIOR_ASSOC.COMPLETIONS,0) AS PRIOR_ASSOC_COMPLETIONS,
    COALESCE(PRIOR_BACH.COMPLETIONS,0) AS PRIOR_BACH_COMPLETIONS,
    COALESCE(PRIOR_CERTS.COMPLETIONS,0) AS PRIOR_CERT_COMPLETIONS,
    COALESCE(PRIOR_MASTERS.COMPLETIONS,0) AS PRIOR_MASTERS_COMPLETIONS,
    COALESCE(PRIOR_DOCTORS.COMPLETIONS,0) AS PRIOR_DOCTORS_COMPLETIONS,
    CURRENT_ASSOC_COMPLETIONS + CURRENT_BACH_COMPLETIONS + CURRENT_CERT_COMPLETIONS + CURRENT_MASTERS_COMPLETIONS + CURRENT_DOCTORS_COMPLETIONS AS CURRENT_COMPLETIONS, -- FF.7.3
    PRIOR_ASSOC_COMPLETIONS + PRIOR_BACH_COMPLETIONS + PRIOR_CERT_COMPLETIONS + PRIOR_MASTERS_COMPLETIONS + PRIOR_DOCTORS_COMPLETIONS AS PRIOR_COMPLETIONS,
    CURRENT_COMPLETIONS - PRIOR_COMPLETIONS AS RAW_CHANGE_COMPLETIONS, -- FF.7.4
    DIV0(CURRENT_COMPLETIONS - PRIOR_COMPLETIONS, PRIOR_COMPLETIONS) AS PCT_CHANGE_COMPLETIONS, -- FF.7.4
    ACS_DATA.POVERTY_LEVEL_PCT AS POVERTY_LEVEL -- FF.9.1
FROM CURR_YEAR
LEFT JOIN 
    PRIOR_YEAR 
ON 
    CURR_YEAR.AREAID = PRIOR_YEAR.AREAID
LEFT JOIN 
    CURR_YEAR_POP 
ON 
    CURR_YEAR.AREAID = CURR_YEAR_POP.AREAID
LEFT JOIN 
    PRIOR_YEAR_POP 
ON 
    CURR_YEAR.AREAID = PRIOR_YEAR_POP.AREAID
LEFT JOIN 
    CURR_JOB_POSTINGS 
ON 
    CURR_YEAR.AREAID = CURR_JOB_POSTINGS.AREAID
LEFT JOIN 
    CURR_ROLLING_JOB_POSTINGS 
ON 
    CURR_YEAR.AREAID = CURR_ROLLING_JOB_POSTINGS.AREAID
LEFT JOIN 
    PRIOR_ROLLING_JOB_POSTINGS 
ON 
    CURR_YEAR.AREAID = PRIOR_ROLLING_JOB_POSTINGS.AREAID
LEFT JOIN 
    CURR_ENROLLMENT 
ON 
    CURR_YEAR.AREAID = CURR_ENROLLMENT.AREAID
LEFT JOIN 
    PRIOR_ENROLLMENT 
ON 
    CURR_YEAR.AREAID = PRIOR_ENROLLMENT.AREAID
LEFT JOIN 
    CURR_ASSOC 
ON 
    CURR_YEAR.AREAID = CURR_ASSOC.AREAID
LEFT JOIN 
    CURR_BACH 
ON 
    CURR_YEAR.AREAID = CURR_BACH.AREAID
LEFT JOIN 
    CURR_CERTS 
ON 
    CURR_YEAR.AREAID = CURR_CERTS.AREAID
LEFT JOIN 
    CURR_DOCTORS 
ON 
    CURR_YEAR.AREAID = CURR_DOCTORS.AREAID
LEFT JOIN 
    CURR_MASTERS 
ON 
    CURR_YEAR.AREAID = CURR_MASTERS.AREAID
LEFT JOIN 
    PRIOR_ASSOC 
ON 
    CURR_YEAR.AREAID = PRIOR_ASSOC.AREAID
LEFT JOIN 
    PRIOR_BACH 
ON 
    CURR_YEAR.AREAID = PRIOR_BACH.AREAID
LEFT JOIN 
    PRIOR_CERTS 
ON 
    CURR_YEAR.AREAID = PRIOR_CERTS.AREAID
LEFT JOIN 
    PRIOR_DOCTORS 
ON 
    CURR_YEAR.AREAID = PRIOR_DOCTORS.AREAID
LEFT JOIN 
    PRIOR_MASTERS 
ON 
    CURR_YEAR.AREAID = PRIOR_MASTERS.AREAID
LEFT JOIN 
    ACS_DATA 
ON 
    CURR_YEAR.AREAID = ACS_DATA.AREAID
