#!/usr/bin/env python3
"""Derive src/owcdata/pipelines/enrollment/scrape.py from the pristine original.

The design commits to carrying the enrollment script over with its parsing,
reshaping, and caching logic unchanged, and to `make diff-enrollment` showing
the complete change set. That commitment is only as good as the file, so the
derivation is executable: this script regenerates scrape.py from
tests/fixtures/primary_enrollment_data_script.original.py by applying an
explicit, ordered list of substitutions.

Every substitution must match exactly once or the script fails — so if someone
edits the original, or a formatter rewraps a line this depends on, that shows
up here rather than silently.

    python scripts/derive_scrape.py --check   # CI: verify scrape.py is current
    python scripts/derive_scrape.py           # rewrite scrape.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ORIGINAL = REPO / "tests/fixtures/primary_enrollment_data_script.original.py"
TARGET = REPO / "src/owcdata/pipelines/enrollment/scrape.py"

HEADER = '''# ===========================================================================
# CARRIED OVER FROM owc_enrollment_data_script/primary_enrollment_data_script.py
#
# Every parsing, reshaping, and caching rule below is unchanged. The pristine
# original is kept at tests/fixtures/primary_enrollment_data_script.original.py
# and `make diff-enrollment` prints the exact change set, which is:
#
#   1. DOWNLOAD_DIR / SOURCE_DIR are set by configure() instead of hardcoded
#      to "data", and the makedirs() calls moved there out of import time. In
#      production these point at a GCS bucket mounted with FUSE, which is what
#      lets os.path.exists() keep working and preserves Step 1b's cache
#      across ephemeral containers with no change to the caching logic.
#   2. Failures are recorded in SKIPS as well as printed. The original printed
#      "[skip]" and continued, so a fiscal year could vanish from the merged
#      CSV leaving no trace outside stdout. Cloud Run reads success from the
#      exit code, so an invisible skip means a permanently green alert.
#   3. main() returns a RunResult instead of None, and raises
#      NoSourceFilesFound when discovery finds nothing. "Found zero files" is
#      the exact signature of Oklahoma redesigning this page and is the most
#      likely failure this pipeline will ever have; the original printed
#      "Nothing to do." and returned normally.
#   4. Three no-op-by-default hooks — ON_PAGE_HTML, ON_FILE_DOWNLOADED, and
#      DOWNLOAD_DELAY_SECONDS — so the caller can snapshot the page HTML,
#      archive the raw workbooks, and space out downloads without this file
#      knowing anything about GCS.
#
# Nothing else. No selector, no sheet-name preference, no column mapping, no
# grade or year formatting rule, and no cache decision was touched.
#
# This file is GENERATED by scripts/derive_scrape.py and is excluded from
# ruff format on purpose: reformatting it would rewrap lines in the original
# parsing code and make the change set above unreadable.
#
# Requires: requests, pandas, beautifulsoup4, openpyxl, xlrd
# (xlrd is only used for the pre-2019 legacy .xls workbooks still linked
# on the page; openpyxl reads everything from 2019 onward)
# ===========================================================================
import os
import re
import time
import urllib.parse
from collections.abc import Callable
from dataclasses import dataclass, field

import pandas as pd
import requests
from bs4 import BeautifulSoup

from owcdata.errors import NoSourceFilesFound, PipelineError, WorkbookReshapeError
'''

CONFIG_BLOCK = '''SOURCE_DIR = os.path.join(DOWNLOAD_DIR, "data_sources")

# Unchanged from the original: oklahoma.gov has served this User-Agent for
# years and there is no upside to being a new stranger to their WAF.
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; PythonScript/1.0)"}

# Seconds between workbook downloads. The original had none and fetched a
# dozen files in a burst; this is politeness toward a small state web property.
DOWNLOAD_DELAY_SECONDS = 0.0

# Called with the page HTML right after it is fetched and before it is parsed,
# so a parsing break can be diagnosed by diffing snapshots instead of by
# re-reading this file. Set by run.py; a no-op when running standalone.
ON_PAGE_HTML: Callable[[str], None] | None = None

# Called with (local_path, url) after a workbook is freshly downloaded, so the
# raw original can be archived immutably and reprocessed without re-scraping.
ON_FILE_DOWNLOADED: Callable[[str, str], None] | None = None


# ---------------------------------------------------------------------------
# Failure recording. Cloud Run reads task success from the exit code, so a
# "[skip]" that only ever reached stdout was a failure nobody could alert on.
# Each entry's `kind` is the event name the log-based metrics match against.
# ---------------------------------------------------------------------------
SKIPS: list[dict] = []
WARNINGS: list[dict] = []


def _record_skip(kind: str, detail: str) -> None:
    """A file we expected to process and did not. Fails the run."""
    SKIPS.append({"kind": kind, "detail": detail})


def _record_warning(kind: str, detail: str) -> None:
    """Something changed but the fallback still produced data. Logged only."""
    WARNINGS.append({"kind": kind, "detail": detail})


@dataclass
class RunResult:
    """What main() produced, so the caller can decide the exit code."""

    records: list = field(default_factory=list)
    merged_path: str | None = None
    merged_rows: int = 0
    reshaped_files: int = 0
    short_circuited: bool = False
    skips: list = field(default_factory=list)
    warnings: list = field(default_factory=list)


def configure(download_dir, delay_seconds: float = 0.0) -> None:
    """Point the cache and output at `download_dir` and create both levels.

    Production passes the FUSE mount point; a local run passes a gitignored
    directory. Because only these two globals move, every os.path.exists()
    cache decision below works unchanged.
    """
    global DOWNLOAD_DIR, SOURCE_DIR, DOWNLOAD_DELAY_SECONDS
    DOWNLOAD_DIR = str(download_dir)
    SOURCE_DIR = os.path.join(DOWNLOAD_DIR, "data_sources")
    DOWNLOAD_DELAY_SECONDS = delay_seconds
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    os.makedirs(SOURCE_DIR, exist_ok=True)


def reset_state() -> None:
    """Clear recorded skips/warnings. Called per run so a second run in the
    same process does not inherit the first one's failures."""
    SKIPS.clear()
    WARNINGS.clear()
'''

# (old, new) — each must match exactly once, applied in order.
SUBSTITUTIONS: list[tuple[str, str]] = [
    # 1. header and imports
    (
        '''# Requires: pip install requests pandas, beautifulsoup4, openpyxl, xlrd
# (xlrd is only used for the pre-2019 legacy .xls workbooks still linked
# on the page; openpyxl reads everything from 2019 onward)
import os
import re
import urllib.parse

import pandas as pd
import requests
from bs4 import BeautifulSoup
''',
        HEADER,
    ),
    # 2a. configurable download dir, no import-time side effect
    (
        '''DOWNLOAD_DIR = "data"
os.makedirs(DOWNLOAD_DIR, exist_ok=True)
''',
        '''# Set by configure(). "data" is the original default and is what a local run
# still gets, though under a separate root so a local test cannot corrupt the
# GCS-backed production cache.
DOWNLOAD_DIR = "data"
''',
    ),
    # 2b. source dir, hooks, failure recording, RunResult, configure()
    (
        '''SOURCE_DIR = os.path.join(DOWNLOAD_DIR, "data_sources")
os.makedirs(SOURCE_DIR, exist_ok=True)

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; PythonScript/1.0)"}
''',
        CONFIG_BLOCK,
    ),
    # 3. the grid-wrapper fallback is the first sign of a page restructure
    (
        '''        print(f"  Warning: no <div class=\\"{' '.join(GRID_WRAPPER_CLASSES)}\\"> "
              f"wrapper found — searching the whole page instead")
        wrappers = [soup]''',
        '''        print(f"  Warning: no <div class=\\"{' '.join(GRID_WRAPPER_CLASSES)}\\"> "
              f"wrapper found — searching the whole page instead")
        # Recorded, not fatal: the whole-page fallback usually still finds the
        # links. But this is the first thing that changes when Oklahoma
        # restructures the page, so it must not stay invisible.
        _record_warning("grid_wrapper_not_found",
                        f"page has no {' '.join(GRID_WRAPPER_CLASSES)} wrapper")
        wrappers = [soup]''',
    ),
    # 4. snapshot the page before parsing it
    (
        '''    resp = requests.get(page_url, headers=HEADERS, timeout=60)
    resp.raise_for_status()  # fatal: 4xx/5xx halts the script here

    soup = BeautifulSoup(resp.text, "html.parser")''',
        '''    resp = requests.get(page_url, headers=HEADERS, timeout=60)
    resp.raise_for_status()  # fatal: 4xx/5xx halts the script here

    # Snapshot before parsing, so the snapshot exists even when parsing is
    # what fails. Pennies of storage; turns a break into a diff.
    if ON_PAGE_HTML is not None:
        ON_PAGE_HTML(resp.text)

    soup = BeautifulSoup(resp.text, "html.parser")''',
    ),
    # 5. download politeness, recorded failure, immutable archive
    (
        '''                try:
                    file_resp = requests.get(candidate_url, headers=HEADERS, timeout=60)
                    file_resp.raise_for_status()
                except requests.exceptions.RequestException as exc:
                    print(f"  [skip] {candidate_url} unreachable ({exc}) — next anchor")
                    continue
                with open(local_path, "wb") as f:
                    f.write(file_resp.content)
''',
        '''                if DOWNLOAD_DELAY_SECONDS:
                    time.sleep(DOWNLOAD_DELAY_SECONDS)
                try:
                    file_resp = requests.get(candidate_url, headers=HEADERS, timeout=60)
                    file_resp.raise_for_status()
                except requests.exceptions.RequestException as exc:
                    print(f"  [skip] {candidate_url} unreachable ({exc}) — next anchor")
                    _record_skip("source_file_unreachable", f"{candidate_url}: {exc}")
                    continue
                with open(local_path, "wb") as f:
                    f.write(file_resp.content)
                # Archive the raw original immutably: reprocess without
                # re-scraping, and keep a record of what the state actually
                # published, which matters if they later revise a file.
                if ON_FILE_DOWNLOADED is not None:
                    ON_FILE_DOWNLOADED(local_path, candidate_url)
''',
    ),
    # 6. unreadable workbook
    (
        '''            except Exception as exc:
                print(f"  [skip] {candidate_url} is not a readable workbook ({exc})")
                continue''',
        '''            except Exception as exc:
                print(f"  [skip] {candidate_url} is not a readable workbook ({exc})")
                _record_skip("workbook_unreadable", f"{candidate_url}: {exc}")
                continue''',
    ),
    # 7. sheet layout no longer matches
    (
        '''            if sheet_name is None or header_row is None:
                print(f"  [skip] {candidate_url} has no matching sheet — next anchor")
                continue''',
        '''            if sheet_name is None or header_row is None:
                print(f"  [skip] {candidate_url} has no matching sheet — next anchor")
                # A workbook whose sheet layout no longer matches. Same class
                # of failure as a page redesign, one level down.
                _record_skip("no_matching_sheet", f"{candidate_url} (pattern {pattern})")
                continue''',
    ),
    # 8. a value column that vanished after the sheet was accepted
    (
        '''    if missing:
        print(f"  Warning: race/gender columns not found and skipped: {missing}")''',
        '''    if missing:
        print(f"  Warning: race/gender columns not found and skipped: {missing}")
        # Header detection only accepts a sheet whose columns match a known
        # signature in full, so a missing value column here means the
        # workbook changed shape after it was accepted — silent data loss.
        _record_skip("missing_race_gender_columns",
                     f"{record['local_path']}: {missing}")''',
    ),
]

# main() is replaced wholesale — it is the only function whose control flow
# changes, because returning None was the bug.
MAIN_OLD = '''def main():
    records, companions_by_year = discover_enrollment_files(PAGE_URL)
    if not records:
        print("No matching files were found on the page. Nothing to do.")
        return

    merged_out_path = os.path.join(DOWNLOAD_DIR, "primary_enrollment_data.csv")

    if all(r["cached"] for r in records):'''

MAIN_NEW = '''def main() -> RunResult:
    """Unchanged pipeline, but it now reports what happened.

    Returns a RunResult and raises NoSourceFilesFound on an empty discovery.
    The original returned None in three places -- zero files discovered, zero
    files reshaped, and the cache short-circuit -- which the shell could not
    tell apart from success.
    """
    reset_state()
    records, companions_by_year = discover_enrollment_files(PAGE_URL)
    if not records:
        # NOT "Nothing to do." This is what Oklahoma redesigning the page
        # looks like, and it is the most likely failure this pipeline has.
        print("No matching files were found on the page.")
        raise NoSourceFilesFound(
            f"discovery found 0 matching files at {PAGE_URL} -- "
            "the page structure has probably changed"
        )

    merged_out_path = os.path.join(DOWNLOAD_DIR, "primary_enrollment_data.csv")

    if all(r["cached"] for r in records):'''

SHORT_CIRCUIT_OLD = '''        cleanup_download_dir(merged_out_path, quiet=True)
        cleanup_source_dir((r["local_path"] for r in records), quiet=True)
        print("\\nDone.")
        return
'''

SHORT_CIRCUIT_NEW = '''        cleanup_download_dir(merged_out_path, quiet=True)
        cleanup_source_dir((r["local_path"] for r in records), quiet=True)
        print("\\nDone.")
        # A short-circuit is a successful run: the cache is intact and
        # nothing new was published. This is the expected outcome in most
        # months, so it must not look like a failure.
        return RunResult(
            records=records,
            merged_path=merged_out_path if os.path.exists(merged_out_path) else None,
            short_circuited=True,
            skips=list(SKIPS),
            warnings=list(WARNINGS),
        )
'''

RESHAPE_SKIP_OLD = '''        except Exception as exc:
            print(f"  [skip] {record['local_path']} failed to reshape ({exc})")
            continue
'''

RESHAPE_SKIP_NEW = '''        except Exception as exc:
            print(f"  [skip] {record['local_path']} failed to reshape ({exc})")
            # Alert #7. Previously this path was invisible: a fiscal year
            # could drop out of the merged CSV with no signal at all.
            _record_skip("workbook_reshape_skipped", f"{record['local_path']}: {exc}")
            continue
'''

NO_FRAMES_OLD = '''    if not reshaped_frames:
        print("No files reshaped successfully. Nothing to merge.")
        return
'''

NO_FRAMES_NEW = '''    if not reshaped_frames:
        print("No files reshaped successfully. Nothing to merge.")
        # Files were discovered but none survived reshape -- the merged CSV
        # would be stale, so this cannot report success either.
        raise WorkbookReshapeError(
            f"all {len(records)} discovered file(s) failed to reshape"
        )
'''

TAIL_OLD = '''    cleanup_source_dir(r["local_path"] for r in records)
    print("\\nDone.")

if __name__ == "__main__":
    main()'''

TAIL_NEW = '''    cleanup_source_dir(r["local_path"] for r in records)
    print("\\nDone.")

    return RunResult(
        records=records,
        merged_path=merged_out_path,
        merged_rows=len(merged),
        reshaped_files=len(reshaped_frames),
        skips=list(SKIPS),
        warnings=list(WARNINGS),
    )


if __name__ == "__main__":
    # Standalone use keeps working, now with a real exit code. The supported
    # entry point is `owcdata run enrollment`.
    import sys

    configure(DOWNLOAD_DIR)
    try:
        _result = main()
    except PipelineError as _exc:
        print(f"FAILED: {_exc}")
        sys.exit(_exc.exit_code)
    if _result.skips:
        print(f"FAILED: {len(_result.skips)} file(s) were skipped")
        sys.exit(WorkbookReshapeError.exit_code)'''

SUBSTITUTIONS += [
    (MAIN_OLD, MAIN_NEW),
    (SHORT_CIRCUIT_OLD, SHORT_CIRCUIT_NEW),
    (RESHAPE_SKIP_OLD, RESHAPE_SKIP_NEW),
    (NO_FRAMES_OLD, NO_FRAMES_NEW),
    (TAIL_OLD, TAIL_NEW),
]


def derive() -> str:
    source = ORIGINAL.read_text(encoding="utf-8")
    for index, (old, new) in enumerate(SUBSTITUTIONS, start=1):
        count = source.count(old)
        if count != 1:
            raise SystemExit(
                f"substitution {index} matched {count} times, expected exactly 1.\n"
                f"The original script has changed, or a formatter rewrapped a line "
                f"this derivation depends on.\n--- expected to find ---\n{old[:400]}"
            )
        source = source.replace(old, new)
    return source


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if scrape.py differs from the derivation")
    args = parser.parse_args()

    derived = derive()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != derived:
            print(
                f"{TARGET.relative_to(REPO)} is not what scripts/derive_scrape.py "
                "produces.\nRun `python scripts/derive_scrape.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(REPO)} is up to date")
        return 0

    TARGET.write_text(derived, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO)} ({len(SUBSTITUTIONS)} substitutions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
